routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GameController@init')->name('game');

Auth::routes(['verify' => true]);

Route::get('/sentence', 'HomeController@index')->name('home')->middleware('verified');

Route::resource('/sentence', 'SentenceController')->middleware('verified');

Route::get('/global-sentence', 'SentenceController@global')->name('sentence.global')->middleware('verified');

Route::resource('/category', 'CategoryController')->middleware('admin');

Route::post('/start-game', 'GameController@start')->name('game.start');

Route::post('/click-letter', 'GameController@clickLetter')->name('game.letter');

Route::post('/change-theme', 'GameController@theme')->name('game.theme');

Route::post('/force-win', 'GameController@forceWin')->name('game.win');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/read-me', 'HomeController@readMe')->name('read.me');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Category extends Model
{
    protected $fillable = ['name'];

    /**
     * @return BelongsToMany
     */
    public function sentence(): BelongsToMany
    {
        return $this->belongsToMany(Sentence::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryValidation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('category.index')->with('alert')->with('categories', Category::get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.form')->with('category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryValidation $request)
    {
        $category = new Category($request->all());
        $category->name = $request->name;
        $category->save();
        return view('category.index')->with('alert', 'Dodano nową kategorię.')->with('categories', Category::get());
    }

    /**
     * Display the specified resource.
     *
     * @param Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return redirect(route('sentence.index'))->with('alert')->with('categories', Category::get());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sentence $sentence
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Category $category)
    {
        return view('category.form')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryValidation $request
     * @param Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryValidation $request, Category $category)
    {
        $category->fill($request->all());
        $category->save();
        return view('category.index')->with('alert', 'Zedytowano kategorię')->with('categories', Category::get());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return view('category.index')->with('alert', 'Usunięto kategorię')->with('categories', Category::get());
    }
}

resources/views/category/form.blade.php
@extends('home')

@section('main')
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if ($errors->any())
                <div class="alert alert-danger">
                        Formularz zawiera błędy!
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <b>{{ $category ? 'Edytuj kategorię' : 'Dodaj nową kategorię' }}</b>
                </div>
                <div class="card-body">
                    {{ Form::model($category, ['route' => ['category.'. ( $category ? 'update':'store'), $category], 'method' => ( $category ? 'put' : 'post')])}}
                    <div class="form-group">
                        {{ Form::label('name', 'Nazwa kategorii: ') }}
                        {{ Form::text('name', $category ? $category->name : null, ['class' => 'form-control '. ($errors->has('name') ? 'is-invalid' : ''), 'required' => 'required']) }}
                        {{ Form::error('name') }}
                    </div>
                    {{ Form::submit('Dodaj', ['class' => 'btn btn-success']) }}
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('home')

@section('main')
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            @endif
            @if($alert !== null)
                <div class="alert alert-danger" role="alert">
                    {{ $alert }}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                     <span class="header-title">Wszystkie kategorie</span><span class="float-right"><a href="{{ route('category.create') }}"><button class="btn btn-success btn-small"><i class="fas fa-plus-circle"></i> Dodaj</button></a></span>
                </div>
                <div class="card-body">
                    <table class="table panel-table">
                        @foreach($categories as $category)
                            <tr>
                                <td>
                                    <span class="float-left">{{ $category->name }}</span>
                                    {{ Form::open(['route' => ['category.destroy', $category], 'method' => 'delete']) }}
                                        <span class="float-right">
                                            <a href="{{ route('category.edit', $category) }}">
                                                <span class="btn btn-link"><i class="fas fa-edit fa-lg text-warning"></i></span>
                                            </a>
                                            <button type="submit" class="btn btn-link"><i class="fas fa-trash-alt fa-lg text-danger ml-3 "></i></button>
                                        </span>
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection