routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GameController@init')->name('game');

Auth::routes(['verify' => true]);

Route::get('/sentence', 'HomeController@index')->name('home')->middleware('verified');

Route::resource('/sentence', 'SentenceController')->middleware('verified');

Route::get('/global-sentence', 'SentenceController@global')->name('sentence.global')->middleware('verified');

Route::resource('/category', 'CategoryController')->middleware('admin');

Route::post('/start-game', 'GameController@start')->name('game.start');

Route::post('/click-letter', 'GameController@clickLetter')->name('game.letter');

Route::post('/change-theme', 'GameController@theme')->name('game.theme');

Route::post('/force-win', 'GameController@forceWin')->name('game.win');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/read-me', 'HomeController@readMe')->name('read.me');

app/Sentence.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * App\Sentence
 *
 * @property-read \App\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Sentence byUser(\App\User $user = null)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Sentence newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Sentence newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Sentence query()
 * @mixin \Eloquent
 */
class Sentence extends Model
{
    protected $fillable = ['text', 'category_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Scope a query to only user's sentences or global
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     * @param  User|null $user
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeByUser($query, User $user = null): Builder
    {
        if (!$user) {
            return $query->whereNull('user_id');
        }
        return $query->where('user_id', $user->id)->orWhereNull('user_id');
    }

    public function setTextAttribute($value)
    {
        $this->attributes['text'] = mb_strtoupper($value, 'UTF-8');
    }
}

app/Http/Controllers/SentenceController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\SentenceValidation;
use App\Sentence;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SentenceController extends Controller
{
    private function getSentences(){
        if (Auth::user()->admin){
            return Sentence::get();
        }
        return Sentence::where('user_id', Auth::user()->id)->get();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('sentence.index')->with('alert')->with('sentences', $this->getSentences());
    }

    public function global()
    {
        return view('sentence.global')->with('alert')->with('sentences', Sentence::where('user_id')->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sentence.form')->with('sentence')->with('categories', Category::all()->pluck('name', 'id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SentenceValidation $request)
    {
        $sentence = new Sentence($request->all());
        $sentence->text = $request->text;
        if (Auth::user()->admin && $request->global) {
            $sentence->user_id = null;
        } else {
            $sentence->user()->associate(Auth::user());
        }
        $sentence->category()->associate($request->category_id);
        $sentence->save();
        return view('sentence.index')->with('alert', 'Dodano nowe zdanie.')->with('sentences', $this->getSentences());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sentence  $sentence
     * @return \Illuminate\Http\Response
     */
    public function show(Sentence $sentence)
    {
        return redirect(route('sentence.index'))->with('alert')->with('sentences', $this->getSentences());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sentence $sentence
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Sentence $sentence)
    {
        $this->authorize($sentence);
        return view('sentence.form')->with('sentence', $sentence)->with('categories', Category::all()->pluck('name', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Sentence $sentence
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(SentenceValidation $request, Sentence $sentence)
    {
        //dd($sentence);
        $this->authorize($sentence);
        $sentence->fill($request->all());
        if (!Auth::user()->admin || !$request->get('global')) {
            $sentence->user()->associate(Auth::user());
        }
        $sentence->save();
        return view('sentence.index')->with('alert', 'Zedytowano zdanie')->with('sentences', $this->getSentences());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sentence $sentence
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Sentence $sentence)
    {
        $this->authorize($sentence);
        $sentence->delete();
        return view('sentence.index')->with('alert', 'Usunięto zdanie')->with('sentences', $this->getSentences());
    }
}

resources/views/sentence/form.blade.php
@extends('home')

@section('main')
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if ($errors->any())
                <div class="alert alert-danger">
                        Formularz zawiera błędy!
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <b>{{ $sentence ? 'Edytuj hasło' : 'Dodaj nowe hasło' }}</b>
                </div>
                <div class="card-body">
                    {{ Form::model($sentence, ['route' => ['sentence.'. ( $sentence ? 'update':'store'), $sentence], 'method' => ( $sentence ? 'put' : 'post')])}}
                    <div class="form-group">
                        {{ Form::label('text', 'Twoje zdanie: ') }}
                        {{ Form::text('text', $sentence ? $sentence->text : null, ['class' => 'form-control '. ($errors->has('text') ? 'is-invalid' : ''), 'required' => 'required']) }}
                        {{ Form::error('text') }}
                    </div>
                    @if(Auth::user()->admin)
                        <div class="form-group">
                            <div>
                                <label>
                                {{ Form::checkbox('global', $sentence, ['class' => 'form-control', 'required' => 'required']) }} Globalne zdanie
                                </label>
                            </div>
                        </div>
                    @endif
                    <div class="form-group">
                        Kategorie:<br>
                        {{ Form::select('category_id', $categories, $sentence ? $sentence->category_id : null, ['class' => 'form-control '. ($errors->has('category_id') ? 'is-invalid' : '')]) }}
                        {{ Form::error('category_id') }}
                    </div>
                    {{ Form::submit('Dodaj', ['class' => 'btn btn-success']) }}
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sentence/global.blade.php
@extends('home')

@section('main')
    <div class="row justify-content-center">
        <div class="col-md-10">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            @endif
            @if($alert !== null)
                <div class="alert alert-danger" role="alert">
                    {{ $alert }}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <span class="header-title">Globalne Hasła</span><span class="float-right"></span>
                </div>
                <div class="card-body">
                    <table class="table panel-table">
                        <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Nazwa</th>
                            <th scope="col">Kategoria</th>
                        </tr>
                        </thead>
                        @foreach($sentences as $sentence)
                            <tr>
                                <td  data-label=""><b>#{{$sentence->id }}</b></td>
                                <td data-label="Nazwa">{{ $sentence->text }}</td>
                                <td data-label="Kategoria" ><span class="mybadge bg-info">{{ $sentence->category->name }}</span></td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sentence/index.blade.php
@extends('home')

@section('main')
    <div class="row justify-content-center">
        <div class="col-md-10">
            @if (session('status'))
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            @endif
            @if($alert !== null)
                <div class="alert alert-danger" role="alert">
                    {{ $alert }}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <span class="header-title">{{ Auth::user()->admin ? 'Wszystkie Hasła' : 'Twoje Hasła' }}</span><span class="float-right"><a href="{{ route('sentence.create') }}"><button class="btn btn-success btn-small"><i class="fas fa-plus-circle"></i> Dodaj</button></a></span>
                </div>
                <div class="card-body">
                    <table class="table panel-table">
                        <thead>
                        <tr>
                            <th scope="col">Nazwa</th>
                            @if(Auth::user()->admin)
                            <th scope="col">Autor</th>
                            @endif
                            <th scope="col">Kategoria</th>
                            <th scope="col">Operacja</th>

                        </tr>
                        </thead>
                        @foreach($sentences as $sentence)
                            <tr>
                                <td data-label="Nazwa"><span class="float-left"><b>#{{$sentence->id }}</b></span> {{ $sentence->text }}</td>
                                @if(Auth::user()->admin)
                                    <td data-label="Autor">{!! $sentence->user_id === null ? '<span class="text-danger">Globalne</span>' : $sentence->user->name !!}</td>
                                @endif
                                <td data-label="Kategoria"><span class="mybadge bg-info">{{ $sentence->category === null ? 'Brak kategorii' : $sentence->category->name }}</span></td>
                                {{ Form::open(['route' => ['sentence.destroy', $sentence], 'method' => 'delete']) }}
                                <td data-label="Operacja" ><a href="{{ route('sentence.edit', $sentence) }}"><span class="btn btn-link"><i class="fas fa-edit fa-lg text-warning"></i></span></a>


                                    <button type="submit" class="btn btn-link"><i class="fas fa-trash-alt fa-lg text-danger ml-3 "></i></button>
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection